version: 2.1

orbs:
  docker: circleci/docker@0.5.2
  helm: circleci/helm@0.1.2

workflows:
  build-deploy-pipeline:
    jobs:
      - build-push-image
      - deploy:
          requires:
            - build-push-image

jobs:
  build-push-image:
    executor: docker/machine
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: naceflabidi/graphql-sample
      - docker/push:
          image: naceflabidi/graphql-sample

  deploy:
    executor: docker/machine
    steps:
      - run:
          name: Prepare certs
          command: |
            echo ${HELM_CA_DATA} | base64 -d > ./ca.pem
            echo ${HELM_CERT_DATA} | base64 -d > ./cert.pem
            echo ${HELM_KEY_DATA} | base64 -d > ./key.pem
      - helm/install-helm-chart:
          release-name: graphql
          chart: ./helm/graphql
          values-to-override: image.tag=$CIRCLE_SHA1
          namespace: graphql
          tls: true
          tls-ca-cert: ./ca.pem
          tls-cert: ./cert.pem
          tls-hostname: https://35.189.123.181
          tls-key: ./key.pem
          tls-verify: true