version: 2.1

orbs:
  docker: circleci/docker@0.5.2
  helm-deploy: perxtech/helm-deploy@0.0.4

workflows:
  build-deploy-pipeline:
    jobs:
      - build-push-image
      - deploy
          requires:
            - build-push-image

jobs:
  build-push-image:
    executor: docker/machine
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: naceflabidi/graphql-sample
      - docker/push:
          image: naceflabidi/graphql-sample

  deploy:
    executor: helm-deploy/default
    steps:
      - helm-deploy/configure-kubectl
      - helm-deploy/deploy:
          helm_release: graphql
          helm_chart: ./helm/graphql
          helm_values: image.tag=$CIRCLE_SHA1